# Generated by Django 4.1.3 on 2022-11-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('current', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('spots', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VroomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.JSONField()),
                ('isActive', models.BooleanField()),
                ('destination', models.CharField(max_length=100)),
                ('current', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
