# Generated by Django 4.1.3 on 2022-11-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vroomVroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rides',
            new_name='Ride',
        ),
    ]
