# Generated by Django 4.1.3 on 2022-11-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vroomVroom', '0002_rename_rides_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='vroomuser',
            name='uname',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
